// report.js v12 — test-mode aware plain text and markdown reports

function reportModeLabel(D) {
  return D.auditMode ? D.auditMode.label : 'Current browser state / unknown';
}

function reportIsPreConsent(D) {
  return !!(D.auditMode && D.auditMode.isPreConsent);
}

function buildFinderySummary(D) {
  var fails = [];
  var warns = [];
  var passes = [];
  var pre = reportIsPreConsent(D);
  var targeting = D.cookies.filter(function(c){return c.category==='Targeting';});

  if (!D.hasCMP) fails.push('NO CONSENT MANAGER DETECTED');
  else passes.push('Consent manager detected: ' + D.cmp);

  passes.push('Consent state tested: ' + reportModeLabel(D));

  if (D.gtmContainers.length > 10) warns.push('EXCESSIVE GTM CONTAINERS (' + D.gtmContainers.length + ') — grade is capped because governance scope must be confirmed');
  else if (D.gtmContainers.length > 5) warns.push('HIGH GTM CONTAINER COUNT (' + D.gtmContainers.length + ') — governance scope should be confirmed');
  else if (D.gtmContainers.length > 1) warns.push('MULTIPLE GTM CONTAINERS (' + D.gtmContainers.length + ') — confirm consent manager governs all relevant containers');
  else if (D.gtmContainers.length === 1) passes.push('1 GTM container detected');

  if (D.det.ga4 && D.consentParams.length === 0 && D.hasCMP && pre) fails.push('GOOGLE CONSENT MODE NOT CONFIRMED in a fresh/denied-style scan');
  else if (D.det.ga4 && D.consentParams.length === 0 && D.hasCMP) warns.push('Google Consent Mode not detected in this selected browser state');
  else if (D.det.ga4 && D.consentParams.length === 0 && !D.hasCMP) fails.push('GOOGLE CONSENT MODE MISSING with no CMP detected');
  else if (D.consentParams.length > 0 && D.hasRestrictedSignals && pre) passes.push('Strong Google restricted/default-denied signals detected: ' + D.consentParams.join(', '));
  else if (D.consentParams.length > 0 && D.hasOnlyGcdSignal && pre) warns.push('Only gcd was detected; restricted/default-denied Google behavior was not proven');
  else if (D.consentParams.length > 0) warns.push('Google Consent Mode indicator detected, but restricted/default-denied state needs verification: ' + D.consentParams.join(', '));

  if (pre && D.analyticsCookieCount > 0) warns.push('ANALYTICS COOKIES PRESENT before consent / after Deny: ' + D.analyticsCookieCount + ' analytics cookies');

  if (D.metaCount > 0 && pre) fails.push('META/FACEBOOK FIRED ' + D.metaCount + ' TIMES in a fresh/denied-style scan');
  else if (D.metaCount > 0) warns.push('Meta/Facebook fired ' + D.metaCount + ' times in this selected browser state');
  else if (pre) passes.push('No Meta/Facebook requests before consent / after Deny');
  else passes.push('No Meta/Facebook requests in this session');

  if (targeting.length > 0 && pre) fails.push('TARGETING COOKIES PRESENT in a fresh/denied-style scan: ' + targeting.map(function(c){return c.name;}).join(', '));
  else if (targeting.length > 0) warns.push('Targeting cookies present in this selected browser state: ' + targeting.map(function(c){return c.name;}).join(', '));
  else if (pre) passes.push('No targeting cookies before consent / after Deny');
  else passes.push('No targeting cookies in this session');

  return { fails: fails, warns: warns, passes: passes };
}

function buildPlainText(D, tips) {
  var date = new Date().toLocaleDateString('en-US', {year:'numeric',month:'long',day:'numeric'});
  var gW = {A:'GREAT',B:'GOOD',C:'FAIR',D:'AT RISK',F:'CRITICAL'};
  var summary = buildFinderySummary(D);
  var lines = [];

  lines.push('CONSENT AUDIT REPORT');
  lines.push('Site: ' + D.hostname);
  lines.push('Date: ' + date);
  lines.push('Grade: ' + D.grade + ' — ' + gW[D.grade]);
  lines.push('Consent state tested: ' + reportModeLabel(D));
  lines.push('Generated by: Consent Auditor (sellone2u-dot.github.io/consent-auditor)');
  lines.push('');

  lines.push('SUMMARY');
  if (summary.fails.length) { lines.push('Fails:'); summary.fails.forEach(function(x){lines.push('  ✗ ' + x);}); }
  if (summary.warns.length) { lines.push('Needs verification:'); summary.warns.forEach(function(x){lines.push('  ⚠ ' + x);}); }
  if (summary.passes.length) { lines.push('Passing:'); summary.passes.forEach(function(x){lines.push('  ✓ ' + x);}); }
  lines.push('');

  lines.push('HEADLINE NUMBERS');
  lines.push('Total requests:       ' + D.totalReqs);
  lines.push('Third-party domains:  ' + D.thirdParty.length);
  lines.push('Cookies detected:     ' + D.cookies.length);
  lines.push('Google requests:      ' + D.googleCount);
  lines.push('Meta requests:        ' + D.metaCount);
  lines.push('');

  lines.push('CONSENT MANAGER');
  lines.push(D.hasCMP ? '✓ ' + D.cmp + ' detected' : '✗ NO CONSENT MANAGER FOUND');
  lines.push(tips.cmp);
  lines.push('');

  if (D.gtmContainers.length > 0) {
    lines.push('GOOGLE TAG MANAGER (' + D.gtmContainers.length + ' containers)');
    D.gtmContainers.forEach(function(id) { lines.push('  ' + id); });
    lines.push(tips.gtm);
    lines.push('');
  }

  lines.push('GOOGLE CONSENT MODE');
  lines.push(D.consentParams.length > 0 ? (D.hasRestrictedSignals ? '✓ Strong restricted signals: ' : '⚠ Signals need verification: ') + D.consentParams.join(' · ') : '⚠ No signals detected');
  lines.push(tips.consentMode);
  lines.push('');

  lines.push('META / FACEBOOK PIXEL');
  lines.push(D.metaCount === 0 ? '✓ No Meta requests in this session' : '⚠ ' + D.metaCount + ' Meta requests fired');
  lines.push(tips.meta);
  lines.push('');

  var essential = D.cookies.filter(function(c){return c.category==='Essential';});
  var analytics = D.cookies.filter(function(c){return c.category==='Analytics';});
  var targeting = D.cookies.filter(function(c){return c.category==='Targeting';});
  lines.push('COOKIES (' + D.cookies.length + ' total)');
  lines.push('Essential: ' + essential.length);
  lines.push('Analytics: ' + analytics.length);
  lines.push('Targeting: ' + targeting.length);
  if (targeting.length) targeting.forEach(function(c){lines.push('  - ' + c.name);});
  lines.push(tips.cookies);
  lines.push('');

  lines.push('QUESTIONS FOR YOUR VENDOR');
  tips.vendorQs.forEach(function(q, i) { lines.push((i+1) + '. ' + q); });
  lines.push('');

  lines.push('RISK ASSESSMENT');
  lines.push(tips.riskSummary);
  lines.push('');
  lines.push('Recommended evidence set: save separate reports for fresh incognito/no choice, Deny cookies, and Accept cookies.');
  lines.push('Note: This report is informational only and does not constitute legal advice.');

  return lines.join('\n');
}

function buildMarkdown(D, tips) {
  var date = new Date().toLocaleDateString('en-US', {year:'numeric',month:'long',day:'numeric'});
  var gW = {A:'Great ✅',B:'Good 🔵',C:'Fair ⚠️',D:'At Risk 🔴',F:'Critical 🚨'};
  var gEmoji = {A:'🟢',B:'🔵',C:'🟡',D:'🔴',F:'🔴'};
  var summary = buildFinderySummary(D);
  var lines = [];
  var pre = reportIsPreConsent(D);

  lines.push('# Consent Audit Report — ' + D.hostname);
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push('| **Site** | ' + D.hostname + ' |');
  lines.push('| **Date** | ' + date + ' |');
  lines.push('| **Grade** | ' + gEmoji[D.grade] + ' **' + D.grade + ' — ' + gW[D.grade] + '** |');
  lines.push('| **Consent State Tested** | **' + reportModeLabel(D) + '** |');
  lines.push('| **Tool** | [Consent Auditor](https://sellone2u-dot.github.io/consent-auditor) |');
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## 🧾 Findings Summary');
  lines.push('');
  if (summary.fails.length) { lines.push('### ❌ Fails'); summary.fails.forEach(function(x){lines.push('- ' + x);}); lines.push(''); }
  if (summary.warns.length) { lines.push('### ⚠️ Needs Verification'); summary.warns.forEach(function(x){lines.push('- ' + x);}); lines.push(''); }
  if (summary.passes.length) { lines.push('### ✅ Passing'); summary.passes.forEach(function(x){lines.push('- ' + x);}); lines.push(''); }

  lines.push('---');
  lines.push('');
  lines.push('## 📊 Headline Numbers');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push('| Total requests | ' + D.totalReqs + ' |');
  lines.push('| Third-party domains | ' + D.thirdParty.length + ' |');
  lines.push('| Cookies detected | ' + D.cookies.length + ' |');
  lines.push('| Google requests | ' + D.googleCount + ' |');
  lines.push('| Meta/Facebook requests | ' + D.metaCount + ' |');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## ' + (D.hasCMP ? '✅' : '🚫') + ' Consent Manager');
  lines.push('');
  lines.push(D.hasCMP ? '**' + D.cmp + ' detected**' : '**NO CONSENT MANAGER FOUND**');
  lines.push('');
  lines.push('> ' + tips.cmp);
  lines.push('');

  if (D.gtmContainers.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## 📦 Google Tag Manager (' + D.gtmContainers.length + ' containers)');
    lines.push('');
    D.gtmContainers.forEach(function(id) { lines.push('- `' + id + '`'); });
    lines.push('');
    lines.push('> ' + tips.gtm);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## ' + (D.consentParams.length > 0 && D.hasRestrictedSignals ? '✅' : '⚠️') + ' Google Consent Mode');
  lines.push('');
  if (D.consentParams.length > 0) lines.push('**Signals detected:** `' + D.consentParams.join('` · `') + '`');
  else lines.push('**No consent mode signals detected**');
  lines.push('');
  lines.push('> ' + tips.consentMode);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## ' + (D.metaCount === 0 ? '✅' : (pre ? '🚨' : '⚠️')) + ' Meta / Facebook Pixel');
  lines.push('');
  lines.push(D.metaCount === 0 ? '**No Meta requests in this session**' : '**' + D.metaCount + ' Meta requests fired**');
  lines.push('');
  lines.push('> ' + tips.meta);
  lines.push('');

  var essential = D.cookies.filter(function(c){return c.category==='Essential';});
  var analytics = D.cookies.filter(function(c){return c.category==='Analytics';});
  var targeting = D.cookies.filter(function(c){return c.category==='Targeting';});
  lines.push('---');
  lines.push('');
  lines.push('## 🍪 Cookies (' + D.cookies.length + ' total)');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');
  lines.push('| Essential | ' + essential.length + ' |');
  lines.push('| Analytics | ' + analytics.length + ' |');
  lines.push('| **Targeting** | **' + targeting.length + '** |');
  if (targeting.length) { lines.push(''); lines.push('**Targeting cookies found:**'); targeting.forEach(function(c){ lines.push('- `' + c.name + '`'); }); }
  lines.push('');
  lines.push('> ' + tips.cookies);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## ❓ Questions for Your Vendor');
  lines.push('');
  tips.vendorQs.forEach(function(q, i) { lines.push((i+1) + '. ' + q); });
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## ⚖️ Risk Assessment');
  lines.push('');
  lines.push('> ' + tips.riskSummary);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 📌 Recommended Evidence Set');
  lines.push('');
  lines.push('- Fresh incognito / no cookie choice report');
  lines.push('- Deny cookies / reject all report');
  lines.push('- Accept cookies / post-consent report');
  lines.push('- Screenshots showing the browser state and key signals such as `gcs`, `npa`, and `pscdl`');
  lines.push('');
  lines.push('*This report is informational only and does not constitute legal advice.*');
  lines.push('*Generated by [Consent Auditor](https://sellone2u-dot.github.io/consent-auditor)*');

  return lines.join('\n');
}
